#
#Mon Jul 06 22:02:13 CEST 2026
_comment=\ ProtoFlow Configuration
_this=C\:\\Dati\\_Laurea Magistrale ISI\\Esami\\07-Paradigmi di Programmazione e Sviluppo (6)\\PPS-25-ProtoFlow\\protoflow\\protoflow.properties
base.folder=C\:\\Dati\\_Laurea Magistrale ISI\\Esami\\07-Paradigmi di Programmazione e Sviluppo (6)\\PPS-25-ProtoFlow\\protoflow
database.folder=C\:\\Dati\\_Laurea Magistrale ISI\\Esami\\07-Paradigmi di Programmazione e Sviluppo (6)\\PPS-25-ProtoFlow\\protoflow\\database
