#
#Sat Jul 25 21:37:20 CEST 2026
_comment=\ ProtoFlow Configuration
_this=C\:\\Users\\rober\\Desktop\\magistrale\\1anno\\2_semestre\\pps\\PPS-25-ProtoFlow\\protoflow\\protoflow.properties
archive.folder=C\:\\Users\\rober\\Desktop\\magistrale\\1anno\\2_semestre\\pps\\PPS-25-ProtoFlow\\protoflow\\archive
base.folder=C\:\\Users\\rober\\Desktop\\magistrale\\1anno\\2_semestre\\pps\\PPS-25-ProtoFlow\\protoflow
database.folder=C\:\\Users\\rober\\Desktop\\magistrale\\1anno\\2_semestre\\pps\\PPS-25-ProtoFlow\\protoflow\\database
ids.folder=C\:\\Users\\rober\\Desktop\\magistrale\\1anno\\2_semestre\\pps\\PPS-25-ProtoFlow\\protoflow\\ids
log.folder=C\:\\Users\\rober\\Desktop\\magistrale\\1anno\\2_semestre\\pps\\PPS-25-ProtoFlow\\protoflow\\log
test.folder=C\:\\Users\\rober\\Desktop\\magistrale\\1anno\\2_semestre\\pps\\PPS-25-ProtoFlow\\protoflow\\test
