name: Test su develop

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  test:
    name: Esecuzione test
    runs-on: ubuntu-latest

    steps:
      - name: Scarica il repository
        uses: actions/checkout@v4

      - name: Configura Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: sbt

      - name: Configura sbt
        uses: sbt/setup-sbt@v1

      - name: Esegui tutti i test
        run: sbt -batch test